Fix/hourly forecast
sunn-shinne/weather-today pull request #18
Opened 2022-07-28 12:51 UTC by GrigoriyYav

- fix: Баг в погоде по часам. Последняя карточка не показывается полностью
- refactor: Сделать равный отступ на страницах до контента
- refactor: Изменен форматы времени, в погоде по часам

2022-07-28 13:43 UTC, akaydo approved these changes

2022-07-29 02:20 UTC, sunn-shinne requested changes
Один момент надо поправить

2022-07-29 02:20 UTC, sunn-shinne commented on src/app/pages/sixteen-days-weather/sixteen-days-weather.component.html
> +    </div>
На моем разрешении экрана спиннер улетает вниз. Тут стоит убрать div обертку и стили .loading с margin-top. Стилей, которые указаны в .spinner, будет достаточно, чтобы спозиционировать спиннер центру

2022-07-29 04:17 UTC, sunn-shinne approved these changes

2022-07-29 04:17 UTC, merged